apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-app-deployment
  labels:
    app: market-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-app
  template:
    metadata:
      labels:
        app: market-app
    spec:
      containers:
        - name: market-app
          image: jmanju/jenkinsuser:latest  # Replace with your actual image if different
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
